export const AGENT_PLUGIN_DEVELOPMENT_DOC_FILENAME = 'guyue-agent-plugin-development.md';

export const AGENT_PLUGIN_DEVELOPMENT_DOC = [
  '# Guyue Master Agent 插件开发标准说明',
  '',
  '本说明用于开发可安装到 Guyue Master 的功能插件，并把插件能力注册给 Agent 调用。当前插件运行在 Electron `webview` 的 sandbox 环境中，通过安全 preload 暴露 `window.guyue`，不开放 Node.js 直接能力。插件、Skill、MCP 只能通过声明式 manifest 和 IPC 能力边界接入，不能直接访问主进程实现。',
  '',
  '## 1. 插件目录结构',
  '',
  '一个插件至少包含：',
  '',
  '```text',
  'my-plugin/',
  '  manifest.json',
  '  index.html',
  '  main.js',
  '  styles.css',
  '```',
  '',
  '安装时选择插件文件夹，应用会复制到用户数据目录的 `plugins/` 下。插件如果只给 Agent 提供工具，也建议保留一个最小 UI，方便用户查看状态和配置。',
  '',
  '## 2. manifest.json',
  '',
  '推荐使用新格式：',
  '',
  '```json',
  '{',
  '  "module": {',
  '    "id": "example-plugin",',
  '    "name": "示例插件",',
  '    "version": "1.0.0",',
  '    "kind": "plugin",',
  '    "description": "一个外部插件示例",',
  '    "icon": "Package",',
  '    "priority": 50,',
  '    "ui": {',
  '      "type": "webview",',
  '      "entry": "index.html",',
  '      "sandbox": true',
  '    },',
  '    "agent": {',
  '      "scopes": [',
  '        {',
  '          "id": "plugin-example-plugin",',
  '          "name": "示例插件",',
  '          "description": "示例插件提供的 Agent 能力",',
  '          "icon": "Package"',
  '        }',
  '      ]',
  '    },',
  '    "events": {',
  '      "publishes": ["example.updated"],',
  '      "subscribes": []',
  '    },',
  '    "commands": {',
  '      "provides": [],',
  '      "consumes": []',
  '    }',
  '  }',
  '}',
  '```',
  '',
  '兼容旧格式：',
  '',
  '```json',
  '{',
  '  "id": "example-plugin",',
  '  "name": "示例插件",',
  '  "version": "1.0.0",',
  '  "description": "一个外部插件示例",',
  '  "icon": "Package",',
  '  "entry": "index.html",',
  '  "author": "you"',
  '}',
  '```',
  '',
  '## 3. 安全 API',
  '',
  '插件页面中可以使用：',
  '',
  '```js',
  'window.guyue.version',
  'window.guyue.plugin.id',
  'window.guyue.events.emit(type, payload)',
  'window.guyue.commands.execute(name, payload)',
  'window.guyue.agent.registerTool(tool, handler)',
  'window.guyue.agent.unregisterTool(name)',
  '```',
  '',
  '插件不能直接访问 Node.js、文件系统、主进程 IPC。需要访问宿主能力时，应通过事件、命令或 Agent 工具协议。',
  '',
  '## 4. 注册 Agent 工具',
  '',
  '```js',
  'await window.guyue.agent.registerTool(',
  '  {',
  '    name: "search_notes",',
  '    description: "在插件自己的笔记数据中搜索内容",',
  '    module: "plugin-example-plugin",',
  '    permission: {',
  '      module: "plugin-example-plugin",',
  '      action: "read"',
  '    },',
  '    inputSchema: {',
  '      type: "object",',
  '      properties: {',
  '        keyword: { type: "string", description: "搜索关键词" }',
  '      },',
  '      required: ["keyword"]',
  '    }',
  '  },',
  '  async (args) => {',
  '    return {',
  '      success: true,',
  '      data: []',
  '    };',
  '  }',
  ');',
  '```',
  '',
  '工具约束：',
  '',
  '- 工具名会自动按插件所有者隔离，避免和内置工具冲突。',
  '- `description` 要直接说明工具能做什么，不要写营销式描述。',
  '- `inputSchema` 必须是 JSON Schema，并尽量声明 `required`。',
  '- `permission.module` 会进入统一权限中心。',
  '- `permission.action` 使用 `read/create/update/delete`。不填时宿主会按工具名推断。',
  '- 需要长期提供给 Agent 的工具应在插件启动阶段注册，不要依赖用户点击某个 UI 按钮后才注册。',
  '',
  '## 5. 权限模型',
  '',
  '插件和内置模块统一进入 Agent 权限中心：',
  '',
  '- `read`：查询、读取、搜索。',
  '- `create`：创建、上传、发送、构建。',
  '- `update`：修改、重命名、移动、状态切换。',
  '- `delete`：删除、清空、移除。',
  '',
  '插件如果提供修改或删除能力，应让工具返回可描述风险的结果。宿主侧会继续保留修改/删除前确认、完全权限和撤销快照机制。',
  '',
  '## 6. 事件和命令',
  '',
  '事件用于模块间松耦合通知：',
  '',
  '```js',
  'await window.guyue.events.emit("example.updated", { id: "1" });',
  '```',
  '',
  '命令用于请求宿主或其他模块执行明确动作：',
  '',
  '```js',
  'const result = await window.guyue.commands.execute("some.command", { id: "1" });',
  '```',
  '',
  '命令总线只执行已注册命令；未注册命令会返回错误。',
  '',
  '## 7. 返回值规范',
  '',
  'Agent 工具建议统一返回：',
  '',
  '```js',
  '{ success: true, data: result }',
  '{ success: false, error: "错误说明" }',
  '```',
  '',
  '不要把异常堆栈直接暴露给模型。涉及敏感数据时，只返回必要字段，密钥、密码、token 不应进入自然语言回复。',
  '',
  '## 8. 设计约束',
  '',
  '- 插件不要假设自己能读取本地文件路径。',
  '- 插件 UI、Agent 工具、事件、命令应分层设计，不要把业务逻辑全部塞进页面点击事件。',
  '- 插件工具应幂等或可恢复，尤其是 `update/delete`。',
  '- 插件内部需要保存密钥时，应在本地 UI 中让用户填写，不要要求用户把密钥发给 Agent 对话。',
  '- 插件应提供清晰的错误信息，便于 Agent 判断是否需要重试、补充参数或请求用户确认。',
].join('\n');
